# Generated by Django 3.1.7 on 2021-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_auto_20210325_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='bb/%Y/%m/%d/1189'),
        ),
    ]
