# Generated by Django 3.1.7 on 2021-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='e_friendship', related_name='_student_friends_+', to='e.Student', verbose_name='친구들'),
        ),
    ]
